# ***** POSTGRES ***** ***** POSTGRES ***** ***** POSTGRES ***** ***** POSTGRES ***** ***** POSTGRES ***** #
version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: estevezdb
    volumes:
      - ./postgres:/var/lib/postgresql/data


# ***** MONGO ***** ***** MONGO ***** ***** MONGO ***** ***** MONGO ***** ***** MONGO ***** ***** MONGO ***** #
# version: '3'

# services:
#   db:
#     image: mongo:5
#     restart: always
#     ports:
#       - 27017:27017
#     environment:
#       MONGODB_DATABASE: mongodb
#     volumes:
#       - ./mongo:/data/db


# ***** MYSQL ***** ***** MYSQL ***** ***** MYSQL ***** ***** MYSQL ***** ***** MYSQL ***** ***** MYSQL ***** #
# version: '3'

# services:
#   db:
#     image: mysql:8.0
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DB_NAME}
#     container_name: mysqldb
#     volumes:
#       - ./mysql:/var/lib/mysql